version: 2
update_configs:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '00:00'
      timezone: 'Asia/Tokyo' # 12am Central Time
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 10
    automerged_updates:
      - match:
          dependency_type: all
          update_type: semver:minor
    reviewers:
      - 'jiyuujin'
    versioning-strategy: 'increase'
